# Generated by Django 5.2.4 on 2025-09-13 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiService', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
        migrations.AddField(
            model_name='login',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='login',
            index=models.Index(fields=['username'], name='login_usernam_41fd9f_idx'),
        ),
        migrations.AlterModelTable(
            name='login',
            table='login',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
