# Generated by Django 5.2.4 on 2025-10-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiService', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='login',
            index=models.Index(fields=['email'], name='login_email_aabf68_idx'),
        ),
    ]
